# Generated by Django 2.1.7 on 2020-05-19 09:32

import ckeditor.fields
import core.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250, verbose_name='Наименование категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='category_images/%Y/%m/%d/', verbose_name='Изображение категории')),
            ],
            options={
                'verbose_name': 'Категории статьи',
                'verbose_name_plural': 'Категория статьи',
                'db_table': 'view_article_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('deleted', models.DateTimeField(default=None, null=True, verbose_name='Дата удаления')),
                ('header', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('image', models.ImageField(blank=True, upload_to='article_images/%Y/%m/%d/', verbose_name='Изображение')),
                ('teaser', models.TextField(max_length=8000, verbose_name='Тизер')),
                ('body', ckeditor.fields.RichTextField(blank=True, default=None, null=True, verbose_name='Текст статьи')),
                ('started', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала показа на сайте')),
                ('ended', models.DateTimeField(verbose_name='Дата завершения показа на сайте')),
                ('hit_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('slug', models.CharField(max_length=255, unique=True, verbose_name='URL')),
                ('products', models.ManyToManyField(related_name='article_products', to='shop.Product', verbose_name='Товары в статье')),
            ],
            options={
                'verbose_name': 'Статья блога',
                'verbose_name_plural': 'Статьи блога',
                'db_table': 'blog_article',
                'ordering': ['-created'],
            },
            bases=(models.Model, core.models.ImagePreviewModelMixin, core.models.AutoIncHitCountModelMixin),
        ),
        migrations.CreateModel(
            name='ArticleSubCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('deleted', models.DateTimeField(default=None, null=True, verbose_name='Дата удаления')),
                ('name', models.CharField(db_index=True, max_length=250, verbose_name='Наименование подкатегории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='article_subcats', to='shop.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатегория статьи',
                'verbose_name_plural': 'Подкатегории статьи',
                'db_table': 'blog_subcategory',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubCatArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('deleted', models.DateTimeField(default=None, null=True, verbose_name='Дата удаления')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Article', verbose_name='Статья')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.ArticleSubCategory', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Подкатегории статьи',
                'verbose_name_plural': 'Подкатегории статьи',
                'db_table': 'blog_subcat_article',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='sub_categories',
            field=models.ManyToManyField(related_name='subcat_articles', through='blog.SubCatArticle', to='blog.ArticleSubCategory', verbose_name='Подкатегории'),
        ),
    ]
