# Generated by Django 2.1.7 on 2020-04-02 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('deleted', models.DateTimeField(default=None, null=True, verbose_name='Дата удаления')),
                ('text', models.TextField(max_length=255, verbose_name='Текст обращения')),
            ],
            options={
                'verbose_name': 'Обращение в техподдержку',
                'verbose_name_plural': 'Обращения в техподдержку',
                'db_table': 'support_request',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='RequestStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('deleted', models.DateTimeField(default=None, null=True, verbose_name='Дата удаления')),
                ('status', models.PositiveIntegerField(choices=[(0, 'На рассмотрении'), (1, 'Запрос информации у пользователя'), (2, 'Закрыто')], default=0, unique=True, verbose_name='Код статуса')),
                ('description', models.CharField(max_length=255, verbose_name='Наименование статуса обращения')),
            ],
            options={
                'verbose_name': 'Статус обращения в техподдержку',
                'verbose_name_plural': 'Статусы обращений в техподдержку',
                'db_table': 'support_request_status',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('deleted', models.DateTimeField(default=None, null=True, verbose_name='Дата удаления')),
                ('description', models.CharField(max_length=255, verbose_name='Наименование типа обращения')),
            ],
            options={
                'verbose_name': 'Тип обращения в техподдержку',
                'verbose_name_plural': 'Типы обращений в техподдержку',
                'db_table': 'support_request_type',
                'ordering': ['description'],
            },
        ),
        migrations.AddField(
            model_name='request',
            name='request_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='support.RequestStatus', verbose_name='Статус обращения'),
        ),
        migrations.AddField(
            model_name='request',
            name='request_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='support.RequestType', verbose_name='Тип обращения'),
        ),
        migrations.AddField(
            model_name='request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
