# Generated by Django 2.1.7 on 2020-05-19 09:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('deleted', models.DateTimeField(default=None, null=True, verbose_name='Дата удаления')),
                ('crm_id', models.BigIntegerField(verbose_name='ID контакта в amoCRM')),
            ],
            options={
                'verbose_name': 'Контакт amoCRM',
                'verbose_name_plural': 'Контакты amoCRM',
                'db_table': 'crm_contact',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('deleted', models.DateTimeField(default=None, null=True, verbose_name='Дата удаления')),
                ('crm_id', models.BigIntegerField(verbose_name='ID сделки в amoCRM')),
            ],
            options={
                'verbose_name': 'Сделка amoCRM',
                'verbose_name_plural': 'Сделки amoCRM',
                'db_table': 'crm_lead',
            },
        ),
        migrations.CreateModel(
            name='RequestsQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(default=None, null=True, verbose_name='Дата удаления')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(default=None, null=True, verbose_name='Дата выполнения')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True, verbose_name='Параметры запроса')),
                ('error_code', models.IntegerField(default=None, null=True, verbose_name='Код ошибки')),
                ('error_desc', models.CharField(default=None, max_length=255, null=True, verbose_name='Описание ошибки')),
                ('comment', models.CharField(default=None, max_length=255, null=True, verbose_name='Примечание')),
                ('in_progress', models.BooleanField(default=False, verbose_name='Признак нахождения запроса в обработке на данный момент')),
                ('restart_count', models.IntegerField(default=0, verbose_name='Количество попыток выполнения')),
                ('response', django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True, verbose_name='Параметры ответа на запрос')),
                ('child_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='amocrm.RequestsQueue', verbose_name='Предшествующий апрос')),
            ],
            options={
                'verbose_name': 'Запрос к amoCRM',
                'verbose_name_plural': 'Запросы к amoCRM',
                'db_table': 'crm_requests_queue',
            },
        ),
        migrations.CreateModel(
            name='RequestStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_status', models.IntegerField(choices=[(0, 'В обработке'), (1, 'Выполнен успешно'), (2, 'Выполнен с ошибкой')], verbose_name='Код статуса запроса')),
                ('description', models.CharField(max_length=255, verbose_name='Описание статуса запроса')),
            ],
            options={
                'verbose_name': 'Статус запроса к amoCRM',
                'verbose_name_plural': 'Статусы запросов к amoCRM',
                'db_table': 'crm_request_status',
            },
        ),
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_type', models.IntegerField(choices=[(0, 'Добавление контакта'), (1, 'Редактирование контакта'), (2, 'Добавление сделки'), (3, 'Редактирование сделки'), (4, 'Аутентификация'), (5, 'Получение данных аккаунта'), (8, 'Получение ID контакта')], verbose_name='Код типа запроса')),
                ('description', models.CharField(max_length=255, verbose_name='Описание типа запроса')),
            ],
            options={
                'verbose_name': 'Тип запроса к amoCRM',
                'verbose_name_plural': 'Типы запросов к amoCRM',
                'db_table': 'crm_request_type',
            },
        ),
        migrations.AddField(
            model_name='requestsqueue',
            name='req_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='amocrm.RequestType', verbose_name='Тип запроса'),
        ),
        migrations.AddField(
            model_name='requestsqueue',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='amocrm.RequestStatus', verbose_name='Статус запроса'),
        ),
    ]
