# Generated by Django 2.1.7 on 2020-05-19 09:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OKSM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=255, verbose_name='Краткое наименование')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное наименование')),
                ('alfa2', models.CharField(max_length=2, verbose_name='Двухсимвольный код')),
                ('alfa3', models.CharField(max_length=2, verbose_name='Трехсимвольный код')),
            ],
            options={
                'db_table': 'core_oksm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bonus1CRawData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('deleted', models.DateTimeField(default=None, null=True, verbose_name='Дата удаления')),
                ('seq_no', models.BigIntegerField(verbose_name='Порядковый номер в массиве запроса')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'core_1c_raw_data',
            },
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('deleted', models.DateTimeField(default=None, null=True, verbose_name='Дата удаления')),
                ('name', models.CharField(max_length=255, verbose_name='Краткое наименование настройки')),
                ('long_name', models.CharField(max_length=255, verbose_name='Полное наименование настройки')),
                ('data_type', models.IntegerField(choices=[(0, 'Текст'), (1, 'Дата/время'), (2, 'Логический тип'), (3, 'Число')], default=0)),
                ('str_val', models.CharField(max_length=255, null=True, verbose_name='Текстовое значение')),
                ('bool_val', models.NullBooleanField(verbose_name='Значение логического типа')),
                ('dt_val', models.DateTimeField(null=True, verbose_name='Значение типа дата/время')),
                ('dec_val', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Значение поля числового типа')),
            ],
            options={
                'verbose_name': 'Настройка сайта, изменяемая администратором',
                'verbose_name_plural': 'Настройки сайта, изменяемые администратором',
                'db_table': 'core_options',
            },
        ),
        migrations.CreateModel(
            name='SendedSMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.CharField(blank=True, max_length=20)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, max_length=255)),
                ('sms_id', models.CharField(blank=True, max_length=255)),
                ('sms_type', models.CharField(blank=True, choices=[(0, 'SMS для подтверждения номер телефона'), (1, 'Информационное SMS'), (2, 'SMS для изменения номера телефона'), (3, 'SMS для изменения пароля'), (4, 'Восстановление доступа')], max_length=20)),
            ],
            options={
                'verbose_name': 'Отправленное SMS',
                'verbose_name_plural': 'Отправленные SMS',
                'db_table': 'core_sended_sms',
            },
        ),
        migrations.CreateModel(
            name='ServiceParam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('deleted', models.DateTimeField(default=None, null=True, verbose_name='Дата удаления')),
                ('service_name', models.CharField(max_length=255, verbose_name='Наименование сервиса')),
                ('param_name', models.CharField(max_length=255, verbose_name='Наименование параметра')),
                ('param_value', models.CharField(max_length=255, verbose_name='Значение параметра')),
            ],
            options={
                'verbose_name': 'Данные для доступа к внешним API',
                'verbose_name_plural': 'Данные для доступа к внешним API',
                'db_table': 'core_service_params',
            },
        ),
    ]
